packages:
  - frontend/frontend-kit/**
  - frontend/testing-view
  - frontend/competition-view
  - frontend/log-view
  - backend
  - electron-app
  - e2e

onlyBuiltDependencies:
  - '@swc/core'
  - core-js-pure
  - electron
  - esbuild
