packages:
  # Frontend packages
  - "frontend/frontend-kit/**"
  - "frontend/testing-view"
  - "frontend/competition-view"

  - "backend"
  - "electron-app"
  - "flashing-view"
  - "packet-sender"
  - "e2e"
