[app]
automatic_window_opening = ""

[vehicle]
boards = [ "BCU", "BLCU" ]

[adj]
branch = "software"
test = false

[network]
manual = false

[transport]
propagate_fault = false

[tcp]
backoff_min_ms = 100
backoff_max_ms = 50_000
backoff_multiplier = 1.5
max_retries = 0
connection_timeout_ms = 1_000
keep_alive_ms = 1_000

[blcu]
ip = "127.0.0.1"
download_order_id = 0
upload_order_id = 0

[tftp]
block_size = 131_072
retries = 3
timeout_ms = 5_000
backoff_factor = 2
enable_progress = true

[logger]
time_unit = "ns"
logging_path = "D:\\GitHub\\software\\electron-app"

# <-- DO NOT TOUCH BELOW THIS LINE -->

# Server Configuration
[server.ethernet-view]
address = "127.0.0.1:4040"
static = "./ethernet-view"

[server.ethernet-view.endpoints]
pod_data = "/podDataStructure"
order_data = "/orderStructures"
programable_boards = "/uploadableBoards"
connections = "/backend"
files = "/"

[server.control-station]
address = "127.0.0.1:4000"
static = "./control-station"

[server.control-station.endpoints]
pod_data = "/podDataStructure"
order_data = "/orderStructures"
programable_boards = "/uploadableBoards"
connections = "/backend"
files = "/"
